title: Lewis Blog
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.1785714
  lightness: 0.625
  brandColors:
    - '#323834'
    - '#90A0C4'
    - '#FFFFD9'
    - '#FBB593'
    - '#B65C38'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Lewis
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.05263158
layout_spectrum: 1
